# Generated by Django 5.0.6 on 2024-05-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
                ('avatarLink', models.CharField(default='', max_length=200)),
                ('idDrive', models.CharField(default='', max_length=100, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.author')),
                ('genres', models.ManyToManyField(to='genre.genre')),
            ],
        ),
    ]
