# Generated by Django 5.0.4 on 2024-05-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0002_manga_avatarlink_manga_description_manga_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="slug",
            field=models.SlugField(default="", max_length=100),
        ),
    ]
