# Generated by Django 5.0.6 on 2024-05-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_manga_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='idDrive',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
