# Generated by Django 5.0.6 on 2024-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default='', max_length=60)),
            ],
        ),
    ]
